//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemTicket.Models.ticket
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTicket
    {
        public int id { get; set; }
        public int id_persona { get; set; }
        public int id_estado_ticket { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string asunto { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> user_ingreso { get; set; }
        public Nullable<int> user_modificacion { get; set; }
    }
}
